apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.app_namespace }}
spec:
  project: {{ .Values.app_project }}
  source:
    repoURL: {{ .Values.app_repo }}
    targetRevision: HEAD
    path: {{ .Values.app_path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.app_namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
