apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xyz
                port:
                  name: xyz
  tls:
    - hosts:
        - xyz
      secretName: tls